development:
  adapter: postgresql
  encoding: unicode
  database: bwf_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bwf_test
  pool: 5
  username: postgres
  password:


